##
##  Makefile -- Build procedure for sample hello_world Apache module
##  Autogenerated via ``apxs -n hello_world -g''.
##
## éQçlÅFhttp://blogs.yahoo.co.jp/take_low_6/23875145.html
##

#
APR_LIB_DIR   :=/usr/lib64
APR_INCLUDEDIR :=/usr/include/apr-1
#
#builddir=.
#top_srcdir=/etc/httpd
#top_builddir=/usr/lib64/httpd
#include /usr/lib64/httpd/build/special.mk
#include  $(top_builddir)/build/config_vars.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#APXS ---------
APXS_CC=`$(APXS) -q CC`
APXS_TARGET=`$(APXS) -q TARGET`
APXS_CFLAGS=`$(APXS) -q CFLAGS`
APXS_SBINDIR=`$(APXS) -q SBINDIR`
APXS_CFLAGS_SHLIB=`$(APXS) -q CFLAGS_SHLIB`
APXS_INCLUDEDIR=`$(APXS) -q INCLUDEDIR`
APXS_LD_SHLIB=`$(APXS) -q LD_SHLIB`
APXS_LIBEXECDIR=`$(APXS) -q LIBEXECDIR`
APXS_LDFLAGS_SHLIB=`$(APXS) -q LDFLAGS_SHLIB`
APXS_SYSCONFDIR=`$(APXS) -q SYSCONFDIR`
APXS_LIBS_SHLIB=`$(APXS) -q LIBS_SHLIB`


#   additional defines, includes and libraries  -llibapriconv-1
#DEFS=-Dmy_define=my_value
INCLUDES = -I. -I$(APR_INCLUDEDIR)/ $(MY_INCLUDES)
LIBS     = -L$(APR_LIB_DIR)/ -lapr-1 -laprutil-1
CXXFLAGS = -I$(APXS_INCLUDEDIR) $(INCLUDES) -static-libgcc -fPIC -iquote $(APXS_CFLAGS) $(APXS_CFLAGS_SHLIB) -Wall
CFLAGS   = -I$(APXS_INCLUDEDIR) $(INCLUDES) -std=c99 -g3 -fPIC
CC       = cc
CPP      = g++
RM       = rm -f




#-----------------------------------------
# display the apxs variables
check_apxs_vars:
	@echo APXS_CC $(APXS_CC);\
	echo APXS_TARGET $(APXS_TARGET);\
	echo APXS_CFLAGS $(APXS_CFLAGS);\
	echo APXS_SBINDIR $(APXS_SBINDIR);\
	echo APXS_CFLAGS_SHLIB $(APXS_CFLAGS_SHLIB);\
	echo APXS_INCLUDEDIR $(APXS_INCLUDEDIR);\
	echo APXS_LD_SHLIB $(APXS_LD_SHLIB);\
	echo APXS_LIBEXECDIR $(APXS_LIBEXECDIR);\
	echo APXS_LDFLAGS_SHLIB $(APXS_LDFLAGS_SHLIB);\
	echo APXS_SYSCONFDIR $(APXS_SYSCONFDIR);\
	echo APXS_LIBS_SHLIB $(APXS_LIBS_SHLIB);\
	echo APR_LIB_DIR $(APR_LIB_DIR)


